/*! header_filters_wiring.js — functional wiring (no page edits needed) */
(function(){
  if (window.__SB_HEADER_WIRING__) return; window.__SB_HEADER_WIRING__ = true;
  const STATE = window.SB_FILTERS = window.SB_FILTERS || { type:null, locationMode:localStorage.getItem('sb_location_mode')||'all', city:localStorage.getItem('sb_city')||'' };
  function $(s,r){return (r||document).querySelector(s)}; function $all(s,r){return Array.from((r||document).querySelectorAll(s))}; function text(s){return (s||'').toLowerCase().trim();}
  document.addEventListener('click', function(e){ const a=e.target.closest('#nav-menu a[data-action]'); if(!a) return; e.preventDefault(); const t=(a.getAttribute('data-action')||'').toLowerCase(); STATE.type=t; window.dispatchEvent(new CustomEvent('sb:filter',{detail:{type:t}})); apply(); }, {passive:false});
  function setSortBy(label){ const selects=$all('select'); for(const sel of selects){ const hit=Array.from(sel.options||[]).find(o=>(o.textContent||o.label||'').trim().toLowerCase()===label.toLowerCase()); if(hit){ sel.value=hit.value; sel.dispatchEvent(new Event('change',{bubbles:true})); return true; } } return false; }
  function hooks(){ if(typeof window.applyFilter==='function'){window.applyFilter(STATE);return true;} if(typeof window.refreshDeals==='function'){window.refreshDeals({filters:STATE});return true;} if(typeof window.fetchDeals==='function'){window.fetchDeals({filters:STATE});return true;} if(typeof window.fetchAll==='function'){window.fetchAll({filters:STATE});return true;} return false; }
  function client(){ const list=$('#deal-list')||$('#deals-list')||$('.deals-list'); if(!list) return false; const cards=$all('[data-deal-id]',list); if(cards.length===0) return false; cards.forEach(el=>el.style.display=''); if(STATE.locationMode==='near'&&STATE.city){ const c=text(STATE.city); cards.forEach(el=>{ const cc=text(el.getAttribute('data-city')); if(!cc||cc!==c) el.style.display='none';}); } if(STATE.type==='mydeals'){ const any=cards.some(el=>el.getAttribute('data-owner')==='1'); if(any) cards.forEach(el=>{ if(el.getAttribute('data-owner')!=='1') el.style.display='none';}); } let key=null; if(STATE.type==='updeals') key='data-upvotes'; if(STATE.type==='populardeals') key=(cards[0]&&('views'in cards[0].dataset))?'data-views':'data-popularity'; if(key){ const vis=cards.filter(el=>el.style.display!=='none'); vis.sort((a,b)=>parseInt(b.getAttribute(key)||'0',10)-parseInt(a.getAttribute(key)||'0',10)); vis.forEach(el=>list.appendChild(el)); } return true; }
  function apply(){ if(hooks()) return; if(STATE.type==='updeals'){ if(setSortBy('Top')) return; } if(STATE.type==='populardeals'){ if(setSortBy('Popular')||setSortBy('Top')) return; } client(); }
  function applyCity(city){ if(!city) return; localStorage.setItem('sb_city',city); localStorage.setItem('sb_location_mode','near'); STATE.city=city; STATE.locationMode='near'; window.dispatchEvent(new CustomEvent('sb:locationFilter',{detail:{mode:'near',city}})); apply(); }
  window.addEventListener('sb:filter', ()=>apply()); window.addEventListener('sb:locationFilter', ()=>apply());
})();