-- Abuse schema (if not present)
ALTER TABLE abuse_reports ADD COLUMN IF NOT EXISTS category VARCHAR(32) DEFAULT 'other';
ALTER TABLE abuse_reports ADD COLUMN IF NOT EXISTS note VARCHAR(255) DEFAULT '';
ALTER TABLE abuse_reports ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP;
